### PR TITLE
Added support for swift package manager.

### PR DESCRIPTION
**Pull request by awilliams88**
❤️

### CODE REVIEW

**Comment by Climbatize** [comment]
Hi @awilliams88 !
Please have a look at my PR: https://github.com/everli/FXPageControl/pull/1
It's fixing an issue with symbolic link (it was elegant but unfortunately only working in your environment) and some small improvements.

**Review by Climbatize — CHANGES_REQUESTED** [review]
The symbolic link on this PR is not working in all environments. I created sent a PR to @awilliams88  https://github.com/everli/FXPageControl/pull/1 to fix it and remove unwanted files that should have been ignored

**Comment by awilliams88** [comment]
@Climbatize thanks - Merged ur PR 🤘💪

**Review by Climbatize — APPROVED** [review]
I use it as a dependency to another lib in production, so looks good to me :)

**Comment by Climbatize** [comment]
Hi @nicklockwood, I know this is a very old project but there are other projects using it as a dependency. It would be awesome if we could merge this one 🙏 🙇

**Comment by guidev** [comment]
+1

**Pull request merged**
