### PR TITLE
Fix changing size when using AutoLayout

### PR DESCRIPTION
**Pull request by herrernst**
after changing values which influence size, call invalidateIntrinsicContentSize so AutoLayout will use new size

### CODE REVIEW

**Comment by mjq** [comment]
+1 for this. Encountered this bug today and can confirm that this patch fixes it.

**Comment by herrernst** [comment]
Thanks, better late than never ;)

**Comment by nicklockwood** [comment]
@herrernst ¯\_(ツ)_/¯

**Comment by herrernst** [comment]
If the other changes are good (haven't looked at them), would you mind issuing a new release (i. e. increase version number), so we can get those changes via Cocoapods? Thanks.

**Pull request merged**
